name: "Traka FernSpähTrp"
title: "Traditionskameradschaft Fernspähtruppe e.V."
description: "Die Traditionskameradschaft Fernspähtruppe e.V. im Bund Deutscher Fallschirmjäger ist eine Gemeinschaft, die parteipolitisch unabhängig fest auf dem Boden des Grundgesetzes steht und sich der Tradition deutschen Soldatentums verpflichtet weis."
logo: '/img/traka_logo.png'
favicon: '/img/traka_site_icon.png'
include: ["_pages"]
permalink: /:title/
url: https://traka-fernspaehtruppe.de

# Jekyll GitHub Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true

# Exclude these files from your production _site 
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
